import { DEFAULT_CHANNEL, DONE_MESSAGE } from './constants.js';
import type { NotifyOptions } from './types.js';

/**
 * Tell the opener the login finished, then close this window.
 *
 * The message carries no payload — not a token, not a user id, nothing. The
 * session is already in a cookie on this origin by the time this runs, so there
 * is nothing to transfer, and a signal that carries no secret cannot leak one.
 *
 * Call this from whatever is served at the callback URL: a dedicated static
 * page (what this app does — see public/auth-popup.html) or a response
 * generated by a worker.
 */
export function notifyDone(options: NotifyOptions = {}): void {
  const { channelName = DEFAULT_CHANNEL, close = true } = options;
  try {
    if (typeof BroadcastChannel !== 'undefined') {
      const channel = new BroadcastChannel(channelName);
      channel.postMessage({ type: DONE_MESSAGE });
      // Safe to close immediately: postMessage has already queued the delivery
      // task on every other channel object.
      channel.close();
    }
  } catch {
    // Channel unavailable (old Safari, hardened context). The opener's
    // focus/visibility fallback still covers us once this window closes.
  }
  if (close) {
    try {
      globalThis.close();
    } catch {
      // Not script-closable. The opener's focus fallback still fires when the
      // user returns to it by hand.
    }
  }
}
