/**
 * Popup sign-in orchestration for AhaSlides apps that delegate login to the
 * platform (`/pages/login`) but do not want a full-page redirect.
 *
 * Two halves, and nothing else: `signIn()` for the window that opens the popup,
 * `notifyDone()` for whatever is served at the callback URL. That callback can
 * be a static page or a response generated by a worker — the opener never
 * inspects it, it only has to call `notifyDone()`.
 *
 * The package is a WINDOW-AND-SIGNAL ORCHESTRATOR, not an auth library. It
 * opens a window, learns when that window finished, and asks the host app to
 * re-check identity. It never sees a password, a token or a cookie, and the one
 * message it sends carries no payload — so adopting it adds nothing to an
 * application's security-critical surface.
 *
 * It cannot log anyone in on its own, and that is a property of the platform,
 * not an omission here: there is no credentials API to call (login is only
 * reachable as a server-rendered page, and the OAuth code exchange needs a
 * client secret that can never reach a browser), and federated providers refuse
 * to render inside an iframe. A real top-level navigation has to happen; all
 * that is left to design is where it lands and how the opener finds out.
 *
 * Proven in aha-elearning's learner sign-in gate before being extracted here.
 */
export { signIn, cancelSignIn } from './signIn.js';
export { notifyDone } from './complete.js';
export { resolveSameOrigin, resolveLoginUrl } from './url.js';
export { DEFAULT_CHANNEL, DEFAULT_WINDOW_NAME, DONE_MESSAGE } from './constants.js';
export type { SignInOptions, SignInOutcome, SignInStatus, NotifyOptions } from './types.js';
