name: 'Build App'
description: 'Builds the application'

inputs:
  repository_url:
    description: "Docker repository URL"
    required: true
  commit_sha:
    description: "Commit SHA for tagging the image"
    required: true
  platform:
    description: "Architecture platform"
    required: false
    default: linux/amd64
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_region:
    description: 'AWS Region'
    required: true
  build_storybook:
    description: 'Whether to build storybook'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Build
      shell: bash
      run: npm run build -- --continue || true

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-builds
        path: apps/**/frontend/dist
        if-no-files-found: warn

    - name: Upload Storybook Artifacts
      if: ${{ inputs.build_storybook == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: storybook-builds
        path: packages/storybook/storybook-static
        if-no-files-found: ignore

    - name: Check Backend Build
      id: check-backend
      shell: bash
      run: |
        if [ -f "packages/backend-main/dist/main.js" ]; then
          echo "build_success=true" >> $GITHUB_OUTPUT
        else
          echo "Backend build failed or missing artifacts."
          echo "build_success=false" >> $GITHUB_OUTPUT
        fi

    - name: Configure AWS Credentials
      if: steps.check-backend.outputs.build_success == 'true'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      if: steps.check-backend.outputs.build_success == 'true'
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image
      if: steps.check-backend.outputs.build_success == 'true'
      run: |
        echo "Building image ${{ inputs.repository_url }}:${{ inputs.commit_sha }}..."
        docker build \
          --platform ${{ inputs.platform }} \
          --push \
          -f packages/backend-main/Dockerfile \
          -t ${{ inputs.repository_url }}:${{ inputs.commit_sha }} .
      shell: bash

