/**
 * This file is AUTO-GENERATED. Do not edit it manually.
 * Generated by scripts/generate-app-module.js
 */
import { Module } from '@nestjs/common';
import { RouterModule } from '@nestjs/core';
import { HealthModule } from './health/health.module';
import { AppModule as SampleSlideModule } from '@aha/sample-slide-backend';

@Module({
  imports: [
    HealthModule,
    SampleSlideModule,
    RouterModule.register([
      {
        path: 'sample-slide',
        module: SampleSlideModule,
      },
    ]),
  ],
})
export class AppModule { }
