/**
 * This file is AUTO-GENERATED. Do not edit it manually.
 * Generated by scripts/generate-app-module.js
 */
import { Module } from '@nestjs/common';
import { MODULE_METADATA } from '@nestjs/common/constants';
import { RouterModule } from '@nestjs/core';
import { HealthModule } from './health/health.module';
import { PluginRegistryModule } from './plugin-registry/plugin-registry.module';
import { AppModule as SampleSlideModule } from '@aha/sample-slide-backend';

// Helper to get all modules imported by a specific module
function getChildModules(targetModule: any) {
  return Reflect.getMetadata(MODULE_METADATA.IMPORTS, targetModule) || [];
}

@Module({
  imports: [
    HealthModule,
    PluginRegistryModule,
    SampleSlideModule,
    RouterModule.register([
      {
        path: 'sample-slide',
        module: SampleSlideModule,
        // This dynamically pulls AiModule and any others without naming them
        children: getChildModules(SampleSlideModule).map(child => ({
          path: '', // Keeps them directly under /ideaBoard/
          module: child
        }))
      },
    ]),
  ],
})
export class AppModule {}
