/**
 * This file is AUTO-GENERATED. Do not edit it manually.
 * Generated by scripts/generate-slide-type-enum.js
 */
export enum SlideType {
  IdeaBoard = 'ideaBoard',
  Markdown = 'markdown',
  PinOnImage = 'pinOnImage',
  Ranking = 'ranking',
  SampleSlide = 'sample-slide',
  Canvas = 'canvas',
  Graph = 'graph',
}
