import { test, expect } from '@fixtures/test';

/**
 * Generated by qa-scaffold. Its job is to prove the whole chain works:
 * config -> env -> fixture -> page object -> browser -> assertion.
 *
 * Replace the assertion with a real landing element for this app, but keep one
 * smoke test here permanently — it is the fastest signal that the harness broke.
 */
test.describe('Smoke', () => {
  test('{{PREFIX}}-TC01: the app loads and renders its shell for an authenticated user', async ({
    homePage,
  }) => {
    await homePage.goto();
    await homePage.waitForReady();

    await expect(homePage.getRoot()).toBeVisible();
  });
});
