import type { LanguageEntry } from './types.js';

/**
 * The canonical AhaSlides language registry — the ONE standard.
 *
 * Every `code` here is ISO 639-1, with a BCP-47 script subtag where a script
 * distinction exists. Where an app uses something else today, the app is
 * non-compliant and that fact lives in `./non-compliance.ts`, NOT here. This
 * file must never grow an app-shaped field again: the moment the standard can
 * express "…and presenter says `kr`", the standard has conceded.
 *
 * SOURCES for the language SET and the dayjs/antd choices (all read from
 * `origin/staging`, re-verified 2026-07-15). Do not edit this file from memory
 * or from a local checkout — see the README's "Adding a language".
 *
 * - language set:
 *     stpancras-presenter-app  src/utils/language/index.js        (`messages`)
 *     stpancras-audience-app   src/utils/language/index.js        (`messages`)
 * - antd pack (Vue):
 *     aha-report               src/utils/language.ts              (`antdLocaleLoaders`)
 * - antd pack (React) + dayjs code:
 *     aha-survey               frontend/src/i18n/applyLocale.ts   (`RESOURCES`)
 *     aha-survey               frontend/src/i18n/localeMapping.ts (`SUPPORTED`)
 *
 * 33 languages. The presenter's `messages` map has 34 keys, but `sl` and `si`
 * both load AhaSlides_Slovenia.json — two codes, one language. `si` is not a
 * 34th language; it is a defect, recorded in the non-compliance record.
 */
export const LANGUAGES: readonly LanguageEntry[] = [
  {
    code: 'en',
    name: 'English',
    dayjs: 'en',
    antd: 'en_US',
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    dayjs: 'vi',
    antd: 'vi_VN',
  },
  {
    code: 'es',
    name: 'Spanish',
    dayjs: 'es',
    antd: 'es_ES',
  },
  {
    code: 'pt',
    name: 'Portuguese',
    dayjs: 'pt-br',
    antd: 'pt_PT',
    notes:
      'CODE SETTLED, DIALECT OPEN — the two halves of the Portuguese question have ' +
      'different answers, and conflating them is the trap this note exists to prevent.\n\n' +
      'THE CODE IS `pt`, by product decision (2026-07). AhaSlides ships ONE Portuguese, ' +
      'so it gets ONE code, and the presenter — the language picker every session is ' +
      'configured from — offers exactly one Portuguese entry: ' +
      "{ name: 'Português', language: 'pt', country: 'Portugal' } in src/constant/index.js. " +
      'There is no Brazilian option to pick. `pt-BR` is therefore not a second language, ' +
      'it is aha-survey coding the same one differently, and it must migrate to `pt`. ' +
      'That entry is actionable now — see NON_COMPLIANCE, app "survey", kind "wrong-code".\n\n' +
      'WHICH Portuguese the CONTENT is remains open, and the registry will not settle it ' +
      'by fiat. It is not the 2–2 app split it looks like. Measured against origin/staging ' +
      'by counting BR/PT lexical markers in the JSON VALUES (the presenter\'s keys are ' +
      'English sentences, so scanning raw file text counts English and gives a wrong ' +
      'answer):\n' +
      '  - presenter AhaSlides_Portuguese.json is a BLEND, not European. It carries both ' +
      '`ficheiro` x34 AND `arquivo` x19 — the same word, "file", translated to both ' +
      'dialects in one file — plus `ecrã` x32 beside `tela` x10. Translated by different ' +
      'hands against different targets.\n' +
      '  - aha-report pt.json is UNCLASSIFIABLE: 169 keys, zero markers either way.\n' +
      '  - audience AhaSlides_Portuguese_BR.json and aha-survey pt-BR are both ' +
      'unambiguously Brazilian (zero European markers between them).\n' +
      'So the presenter points one way by LABEL (country: Portugal) and another by ' +
      'CONTENT (a blend), which is exactly why "just follow the presenter" cannot decide ' +
      'the dialect. See CONTENT_DIVERGENCES: pt.\n\n' +
      'The mismatched `antd`/`dayjs` above is that open dialect showing through, not a ' +
      "typo: antd pt_PT is aha-report's, dayjs pt-br is aha-survey's — the only values " +
      'any app has actually chosen. Do NOT harmonise them; picking one would silently ' +
      'decide the dialect. They resolve when the content question does.',
  },
  {
    code: 'fr',
    name: 'French',
    dayjs: 'fr',
    antd: 'fr_FR',
  },
  {
    code: 'de',
    name: 'German',
    dayjs: 'de',
    antd: 'de_DE',
  },
  {
    code: 'id',
    name: 'Indonesian',
    dayjs: 'id',
    antd: 'id_ID',
    notes:
      'Not offered in the presenter switcher (constant/index.js languageOptions) but ' +
      'loadable via its `messages` map and allowlisted in constant/locale.js. A real ' +
      'language, reachable by a host locale — just not user-selectable in that one UI.',
  },
  {
    code: 'it',
    name: 'Italian',
    dayjs: 'it',
    antd: 'it_IT',
  },
  {
    code: 'tr',
    name: 'Turkish',
    dayjs: 'tr',
    antd: 'tr_TR',
    notes: 'Not in the presenter switcher; loadable via `messages` and constant/locale.js.',
  },
  {
    code: 'ja',
    name: 'Japanese',
    dayjs: 'ja',
    antd: 'ja_JP',
  },
  {
    code: 'nl',
    name: 'Dutch',
    dayjs: 'nl',
    antd: 'nl_NL',
  },
  {
    code: 'ru',
    name: 'Russian',
    dayjs: 'ru',
    antd: 'ru_RU',
  },
  {
    code: 'pl',
    name: 'Polish',
    dayjs: 'pl',
    antd: 'pl_PL',
  },
  {
    code: 'da',
    name: 'Danish',
    dayjs: 'da',
    antd: 'da_DK',
    notes: 'Not in the presenter switcher; loadable via `messages` and constant/locale.js.',
  },
  {
    code: 'zh',
    name: 'Chinese (Simplified)',
    dayjs: 'zh-cn',
    antd: 'zh_CN',
    notes:
      'KNOWN BUG, FILED SEPARATELY — DO NOT "FIX" HERE. `zh` denotes Simplified: the ' +
      'presenter (authority for the language set), its switcher entry (中文/China) and ' +
      "aha-report's zh_CN + zh.json all agree. The audience app serves TRADITIONAL " +
      'under the same `zh` and ships no Simplified file at all, so this cannot be ' +
      'corrected by a registry edit — it needs a content fix in the audience app. ' +
      'Traditional Chinese content exists in three places (an orphaned presenter file, ' +
      "the audience `zh` bundle, aha-report's `zh-tw`) but has no registry language, " +
      'because no *presenter* language covers it. Adopting `zh-TW` as a 34th language ' +
      'is the likely resolution. See the non-compliance record: language "zh".',
  },
  {
    code: 'sl',
    name: 'Slovenian',
    dayjs: 'sl',
    antd: 'sl_SI',
    notes:
      'The canonical code is `sl`. Presenter, audience and team-management ALSO accept ' +
      "`si` for this language, which is why the presenter's `messages` map has 34 keys " +
      'for 33 languages. `si` is the ISO 639-1 code for Sinhala. It is not an alias the ' +
      'registry supports — it is a defect those apps must drop.',
  },
  {
    code: 'lv',
    name: 'Latvian',
    dayjs: 'lv',
    antd: 'lv_LV',
  },
  {
    code: 'cs',
    name: 'Czech',
    dayjs: 'cs',
    antd: 'cs_CZ',
  },
  {
    code: 'ko',
    name: 'Korean',
    dayjs: 'ko',
    antd: 'ko_KR',
    notes:
      'Canonical is the ISO 639-1 `ko`. Four apps use `kr` — the ISO 3166-1 country ' +
      'code for South Korea, and the ISO 639-1 code for KANURI. aha-survey already ' +
      'migrated to `ko` so Intl plural/date rules resolve; the rest must follow.',
  },
  {
    code: 'no',
    name: 'Norwegian',
    dayjs: 'nb',
    antd: 'nb_NO',
    notes:
      'dayjs and antd have no bare `no` — both use Bokmål (nb / nb_NO), the standard ' +
      'written form. `no` is a valid ISO 639-1 macrolanguage code, so it stays canonical.',
  },
  {
    code: 'sv',
    name: 'Swedish',
    dayjs: null,
    antd: 'sv_SE',
    notes:
      'Canonical is the ISO 639-1 `sv`. Four apps use `se` — the ISO 3166-1 country ' +
      'code for Sweden, and the ISO 639-1 code for NORTHERN SAMI. `dayjs` is null ' +
      'because aha-survey is the only source of dayjs codes and it has no Swedish at ' +
      'all; the code was NOT guessed. `antd` sv_SE comes from aha-report.',
  },
  {
    code: 'el',
    name: 'Greek',
    dayjs: 'el',
    antd: 'el_GR',
  },
  {
    code: 'lt',
    name: 'Lithuanian',
    dayjs: 'lt',
    antd: 'lt_LT',
  },
  {
    code: 'hr',
    name: 'Croatian',
    dayjs: 'hr',
    antd: 'hr_HR',
  },
  {
    code: 'is',
    name: 'Icelandic',
    dayjs: 'is',
    antd: 'is_IS',
  },
  {
    code: 'bg',
    name: 'Bulgarian',
    dayjs: 'bg',
    antd: 'bg_BG',
  },
  {
    code: 'ro',
    name: 'Romanian',
    dayjs: 'ro',
    antd: 'ro_RO',
  },
  {
    code: 'sk',
    name: 'Slovak',
    dayjs: 'sk',
    antd: 'sk_SK',
  },
  {
    code: 'hu',
    name: 'Hungarian',
    dayjs: 'hu',
    antd: 'hu_HU',
  },
  {
    code: 'sq',
    name: 'Albanian',
    dayjs: 'sq',
    antd: 'en_US',
    notes:
      'DELIBERATE GAP — DO NOT "FIX". antd ships no Albanian pack, so both aha-report ' +
      'and aha-survey fall back to en_US for built-ins (pagination, pickers, empty ' +
      'states); strings and dates are still Albanian. `antd: "en_US"` records that ' +
      'intentional fallback, it is not a mistake.',
  },
  {
    code: 'az',
    name: 'Azerbaijani',
    dayjs: null,
    antd: null,
    notes:
      'The newest language, and the sharpest example of why this registry exists: it ' +
      'reached presenter + audience and stopped there. dayjs and antd are null because ' +
      'NO app has chosen either yet — they were NOT guessed. Whoever adds `az` to a ' +
      'consumer must pick them deliberately and record them here.',
  },
  {
    code: 'sr-Latn',
    name: 'Serbian (Latin)',
    dayjs: 'sr',
    antd: 'sr_RS',
    notes:
      'Canonical uses BCP-47 script-subtag casing (`sr-Latn`). Four apps write ' +
      '`sr-latn`. Per RFC 5646 §2.1.1 that is the SAME tag — a casing deviation, not a ' +
      'wrong code — so the registry resolves it and the record files it as style.',
  },
  {
    code: 'sr-Cyrl',
    name: 'Serbian (Cyrillic)',
    dayjs: 'sr-cyrl',
    antd: 'sr_RS',
    notes:
      'DELIBERATE GAP — DO NOT "FIX". antd has no Cyrillic Serbian pack, so both ' +
      'aha-report and aha-survey borrow the LATIN-script sr_RS pack; built-ins render ' +
      'in Latin script while strings/dates are Cyrillic. That is the existing, ' +
      'intentional behavior.',
  },
];
