import type { LanguageEntry } from './types.js';

/**
 * The canonical AhaSlides language registry.
 *
 * SOURCES (all read from `origin/staging`, 2026-07-15). Do not edit this file
 * from memory or from a local checkout — see the README's "Adding a language".
 *
 * - language set + presenter code/file:
 *     stpancras-presenter-app  src/utils/language/index.js       (`messages`)
 * - presenter legacy aliases:
 *     stpancras-presenter-app  src/utils/language/index.js       (`br` -> `pt`)
 *     stpancras-presenter-app  src/constant/locale.js            (allowlist)
 * - audience code/file:
 *     stpancras-audience-app   src/utils/language/index.js       (`messages`)
 * - report code:
 *     aha-report               src/utils/language.ts             (`loaders`)
 * - antd pack (Vue):
 *     aha-report               src/utils/language.ts             (`antdLocaleLoaders`)
 * - survey code + antd pack (React) + dayjs code:
 *     aha-survey               frontend/src/i18n/localeMapping.ts (`SUPPORTED`)
 *     aha-survey               frontend/src/i18n/applyLocale.ts   (`RESOURCES`)
 * - team code:
 *     aha-team-management      packages/frontend/src/i18n/index.ts (`supportedLngs`)
 *
 * 33 languages / 34 presenter codes: the presenter's `messages` map has 34 keys
 * but `sl` and `si` both load AhaSlides_Slovenia.json, i.e. they are two codes
 * for one language. `si` is recorded as an alias of `sl`, not a 34th language.
 */
export const LANGUAGES: readonly LanguageEntry[] = [
  {
    code: 'en',
    name: 'English',
    aliases: [],
    apps: { presenter: 'en', audience: 'en', report: 'en', survey: 'en', team: 'en' },
    files: { presenter: 'AhaSlides_English.json', audience: 'AhaSlides_English.json' },
    dayjs: 'en',
    antd: 'en_US',
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    aliases: [],
    apps: { presenter: 'vi', audience: 'vi', report: 'vi', survey: 'vi', team: 'vi' },
    files: { presenter: 'AhaSlides_Vietnamese.json', audience: 'AhaSlides_Vietnamese.json' },
    dayjs: 'vi',
    antd: 'vi_VN',
  },
  {
    code: 'es',
    name: 'Spanish',
    aliases: [],
    apps: { presenter: 'es', audience: 'es', report: 'es', survey: 'es', team: 'es' },
    files: { presenter: 'AhaSlides_Spanish.json', audience: 'AhaSlides_Spanish.json' },
    dayjs: 'es',
    antd: 'es_ES',
  },
  {
    code: 'pt',
    name: 'Portuguese',
    aliases: ['br', 'pt-BR'],
    apps: { presenter: 'pt', audience: 'pt', report: 'pt', survey: 'pt-BR', team: 'pt' },
    files: { presenter: 'AhaSlides_Portuguese.json', audience: 'AhaSlides_Portuguese_BR.json' },
    dayjs: 'pt-br',
    antd: 'pt_PT',
    notes:
      'UNRESOLVED DIVERGENCE — the apps disagree on which Portuguese this is, and the ' +
      'registry records rather than resolves it. Presenter serves European Portuguese ' +
      '(AhaSlides_Portuguese.json; its switcher entry is "Português"/Portugal) and ' +
      'aha-report pairs it with antd pt_PT. Audience serves Brazilian ' +
      '(AhaSlides_Portuguese_BR.json) and aha-survey canonicalizes to pt-BR with antd ' +
      'pt_BR + dayjs pt-br. `antd` here is aha-report\'s pt_PT (it matches the canonical ' +
      '`pt`); `dayjs` is pt-br because aha-survey is the ONLY source of a dayjs code and ' +
      'inventing `pt` would be a guess. That inconsistency is the finding, not a typo. ' +
      '`br` is a legacy presenter alias (presenter index.js rewrites br -> pt); bare ' +
      '`br` is the ISO 639-1 code for Breton.',
  },
  {
    code: 'fr',
    name: 'French',
    aliases: [],
    apps: { presenter: 'fr', audience: 'fr', report: 'fr', survey: 'fr', team: 'fr' },
    files: { presenter: 'AhaSlides_French.json', audience: 'AhaSlides_French.json' },
    dayjs: 'fr',
    antd: 'fr_FR',
  },
  {
    code: 'de',
    name: 'German',
    aliases: [],
    apps: { presenter: 'de', audience: 'de', report: 'de', survey: 'de', team: 'de' },
    files: { presenter: 'AhaSlides_German.json', audience: 'AhaSlides_German.json' },
    dayjs: 'de',
    antd: 'de_DE',
  },
  {
    code: 'id',
    name: 'Indonesian',
    aliases: [],
    apps: { presenter: 'id', audience: 'id', report: 'id', survey: 'id', team: 'id' },
    files: { presenter: 'AhaSlides_id.json', audience: 'AhaSlides_id.json' },
    dayjs: 'id',
    antd: 'id_ID',
    notes:
      'Not in the presenter switcher (constant/index.js languageOptions) but loadable ' +
      'via its `messages` map and listed in constant/locale.js.',
  },
  {
    code: 'it',
    name: 'Italian',
    aliases: [],
    apps: { presenter: 'it', audience: 'it', report: 'it', survey: 'it', team: 'it' },
    files: { presenter: 'AhaSlides_Italian.json', audience: 'AhaSlides_Italian.json' },
    dayjs: 'it',
    antd: 'it_IT',
  },
  {
    code: 'tr',
    name: 'Turkish',
    aliases: [],
    apps: { presenter: 'tr', audience: 'tr', report: 'tr', survey: 'tr', team: 'tr' },
    files: { presenter: 'AhaSlides_Turkish.json', audience: 'AhaSlides_Turkish.json' },
    dayjs: 'tr',
    antd: 'tr_TR',
    notes: 'Not in the presenter switcher; loadable via `messages` and constant/locale.js.',
  },
  {
    code: 'ja',
    name: 'Japanese',
    aliases: [],
    apps: { presenter: 'ja', audience: 'ja', report: 'ja', survey: 'ja', team: 'ja' },
    files: { presenter: 'AhaSlides_Japanese.json', audience: 'AhaSlides_Japanese.json' },
    dayjs: 'ja',
    antd: 'ja_JP',
  },
  {
    code: 'nl',
    name: 'Dutch',
    aliases: [],
    apps: { presenter: 'nl', audience: 'nl', report: 'nl', survey: 'nl', team: 'nl' },
    files: { presenter: 'AhaSlides_Dutch.json', audience: 'AhaSlides_Dutch.json' },
    dayjs: 'nl',
    antd: 'nl_NL',
  },
  {
    code: 'ru',
    name: 'Russian',
    aliases: [],
    apps: { presenter: 'ru', audience: 'ru', report: 'ru', survey: 'ru', team: 'ru' },
    files: { presenter: 'AhaSlides_Russian.json', audience: 'AhaSlides_Russian.json' },
    dayjs: 'ru',
    antd: 'ru_RU',
  },
  {
    code: 'pl',
    name: 'Polish',
    aliases: [],
    apps: { presenter: 'pl', audience: 'pl', report: 'pl', survey: 'pl', team: 'pl' },
    files: { presenter: 'AhaSlides_Polish.json', audience: 'AhaSlides_Polish.json' },
    dayjs: 'pl',
    antd: 'pl_PL',
  },
  {
    code: 'da',
    name: 'Danish',
    aliases: [],
    apps: { presenter: 'da', audience: 'da', report: 'da', survey: 'da', team: 'da' },
    files: { presenter: 'AhaSlides_Danish.json', audience: 'AhaSlides_Danish.json' },
    dayjs: 'da',
    antd: 'da_DK',
    notes: 'Not in the presenter switcher; loadable via `messages` and constant/locale.js.',
  },
  {
    code: 'zh',
    name: 'Chinese (Simplified)',
    aliases: [],
    apps: { presenter: 'zh', audience: 'zh', report: 'zh', survey: 'zh', team: 'zh' },
    files: {
      presenter: 'AhaSlides_Simplified_Chinese.json',
      audience: 'AhaSlides_Traditional_Chinese.json',
    },
    dayjs: 'zh-cn',
    antd: 'zh_CN',
    notes:
      'KNOWN BUG, FILED SEPARATELY — DO NOT "FIX" HERE. The code `zh` means a DIFFERENT ' +
      'LANGUAGE in the two apps: presenter loads AhaSlides_Simplified_Chinese.json ' +
      '(src/utils/language/index.js:23) while audience loads ' +
      'AhaSlides_Traditional_Chinese.json (src/utils/language/index.js:19). The audience ' +
      'app ships NO Simplified Chinese file at all, so this cannot be corrected by a ' +
      'registry edit. The name/dayjs/antd here follow Simplified because the presenter ' +
      '(the authority for the language set), its switcher entry (中文/China) and ' +
      "aha-report's zh_CN + zh.json all say Simplified; the audience file is recorded " +
      'verbatim in `files.audience` so the divergence is visible data. Separately, ' +
      'aha-report has a `zh-tw` (Traditional) locale that exists in NO other app and is ' +
      'therefore not a registry language — see the README.',
  },
  {
    code: 'sl',
    name: 'Slovenian',
    aliases: ['si'],
    apps: { presenter: 'sl', audience: 'sl', report: 'sl', survey: 'sl', team: 'sl' },
    files: { presenter: 'AhaSlides_Slovenia.json', audience: 'AhaSlides_Slovenia.json' },
    dayjs: 'sl',
    antd: 'sl_SI',
    notes:
      '`si` is a legacy alias, not a language: presenter, audience and team-management ' +
      'all map BOTH `sl` and `si` to the Slovenian bundle, and aha-survey maps si -> sl. ' +
      'Bare `si` is the ISO 639-1 code for Sinhala. This is why the presenter\'s ' +
      '`messages` map has 34 keys but only 33 languages.',
  },
  {
    code: 'lv',
    name: 'Latvian',
    aliases: [],
    apps: { presenter: 'lv', audience: 'lv', report: 'lv', survey: 'lv', team: 'lv' },
    files: { presenter: 'AhaSlides_lv.json', audience: 'AhaSlides_lv.json' },
    dayjs: 'lv',
    antd: 'lv_LV',
  },
  {
    code: 'cs',
    name: 'Czech',
    aliases: [],
    apps: { presenter: 'cs', audience: 'cs', report: 'cs', survey: 'cs', team: 'cs' },
    files: { presenter: 'AhaSlides_Czech.json', audience: 'AhaSlides_Czech.json' },
    dayjs: 'cs',
    antd: 'cs_CZ',
  },
  {
    code: 'ko',
    name: 'Korean',
    aliases: ['kr'],
    apps: { presenter: 'kr', audience: 'kr', report: 'kr', survey: 'ko', team: 'kr' },
    files: { presenter: 'AhaSlides_Korean.json', audience: 'AhaSlides_Korean.json' },
    dayjs: 'ko',
    antd: 'ko_KR',
    notes:
      'Canonical is the ISO 639-1 `ko`. Presenter/audience/report/team all use `kr`, ' +
      'which is the ISO 3166 COUNTRY code for South Korea and not a language code at ' +
      'all; aha-survey already migrated to `ko` so Intl plural/date rules resolve.',
  },
  {
    code: 'no',
    name: 'Norwegian',
    aliases: [],
    apps: { presenter: 'no', audience: 'no', report: 'no', survey: 'no', team: 'no' },
    files: { presenter: 'AhaSlides_Norwegian.json', audience: 'AhaSlides_Norwegian.json' },
    dayjs: 'nb',
    antd: 'nb_NO',
    notes:
      'dayjs and antd have no bare `no` — both use Bokmål (nb / nb_NO), the standard ' +
      'written form. `no` is a valid ISO 639-1 macrolanguage code, so it stays canonical.',
  },
  {
    code: 'sv',
    name: 'Swedish',
    aliases: ['se'],
    apps: { presenter: 'se', audience: 'se', report: 'se', survey: null, team: 'se' },
    files: { presenter: 'AhaSlides_Swedish.json', audience: 'AhaSlides_Swedish.json' },
    dayjs: null,
    antd: 'sv_SE',
    notes:
      'Canonical is the ISO 639-1 `sv`. Every app uses `se`, which is the ISO 639-1 code ' +
      'for NORTHERN SAMI — a different language. DRIFT: aha-survey has no Swedish at all ' +
      '(no entry in localeMapping.ts SUPPORTED), so a presenter session in Swedish ' +
      'renders an English survey. `dayjs` is null because aha-survey is the only source ' +
      'of dayjs codes and it has no Swedish entry — the code was NOT guessed. `antd` ' +
      "sv_SE comes from aha-report's antdLocaleLoaders.",
  },
  {
    code: 'el',
    name: 'Greek',
    aliases: [],
    apps: { presenter: 'el', audience: 'el', report: 'el', survey: 'el', team: 'el' },
    files: { presenter: 'AhaSlides_Greek.json', audience: 'AhaSlides_Greek.json' },
    dayjs: 'el',
    antd: 'el_GR',
  },
  {
    code: 'lt',
    name: 'Lithuanian',
    aliases: [],
    apps: { presenter: 'lt', audience: 'lt', report: 'lt', survey: 'lt', team: 'lt' },
    files: { presenter: 'AhaSlides_Lithuanian.json', audience: 'AhaSlides_Lithuanian.json' },
    dayjs: 'lt',
    antd: 'lt_LT',
  },
  {
    code: 'hr',
    name: 'Croatian',
    aliases: [],
    apps: { presenter: 'hr', audience: 'hr', report: 'hr', survey: 'hr', team: 'hr' },
    files: { presenter: 'AhaSlides_Croatian.json', audience: 'AhaSlides_Croatian.json' },
    dayjs: 'hr',
    antd: 'hr_HR',
  },
  {
    code: 'is',
    name: 'Icelandic',
    aliases: [],
    apps: { presenter: 'is', audience: 'is', report: 'is', survey: 'is', team: 'is' },
    files: { presenter: 'AhaSlides_Icelandic.json', audience: 'AhaSlides_Icelandic.json' },
    dayjs: 'is',
    antd: 'is_IS',
  },
  {
    code: 'bg',
    name: 'Bulgarian',
    aliases: [],
    apps: { presenter: 'bg', audience: 'bg', report: 'bg', survey: 'bg', team: 'bg' },
    files: { presenter: 'AhaSlides_Bulgarian.json', audience: 'AhaSlides_Bulgarian.json' },
    dayjs: 'bg',
    antd: 'bg_BG',
  },
  {
    code: 'ro',
    name: 'Romanian',
    aliases: [],
    apps: { presenter: 'ro', audience: 'ro', report: 'ro', survey: 'ro', team: 'ro' },
    files: { presenter: 'AhaSlides_Romanian.json', audience: 'AhaSlides_Romanian.json' },
    dayjs: 'ro',
    antd: 'ro_RO',
  },
  {
    code: 'sk',
    name: 'Slovak',
    aliases: [],
    apps: { presenter: 'sk', audience: 'sk', report: 'sk', survey: 'sk', team: 'sk' },
    files: { presenter: 'AhaSlides_Slovakia.json', audience: 'AhaSlides_Slovak.json' },
    dayjs: 'sk',
    antd: 'sk_SK',
    notes:
      'The two apps ship the same language under DIFFERENT filenames — presenter ' +
      'AhaSlides_Slovakia.json, audience AhaSlides_Slovak.json. Cosmetic (unlike `zh`, ' +
      'both are Slovak) but it is why `files` is per-app.',
  },
  {
    code: 'hu',
    name: 'Hungarian',
    aliases: [],
    apps: { presenter: 'hu', audience: 'hu', report: 'hu', survey: 'hu', team: 'hu' },
    files: { presenter: 'AhaSlides_Hungary.json', audience: 'AhaSlides_Hungary.json' },
    dayjs: 'hu',
    antd: 'hu_HU',
  },
  {
    code: 'sq',
    name: 'Albanian',
    aliases: [],
    apps: { presenter: 'sq', audience: 'sq', report: 'sq', survey: 'sq', team: 'sq' },
    files: { presenter: 'AhaSlides_Albanian.json', audience: 'AhaSlides_Albanian.json' },
    dayjs: 'sq',
    antd: 'en_US',
    notes:
      'DELIBERATE GAP — DO NOT "FIX". antd ships no Albanian pack, so both aha-report ' +
      'and aha-survey fall back to en_US for built-ins (pagination, pickers, empty ' +
      'states); strings and dates are still Albanian. `antd: "en_US"` records that ' +
      'intentional fallback, it is not a mistake.',
  },
  {
    code: 'az',
    name: 'Azerbaijani',
    aliases: [],
    apps: { presenter: 'az', audience: 'az', report: null, survey: null, team: null },
    files: { presenter: 'AhaSlides_Azerbaijani.json', audience: 'AhaSlides_Azerbaijani.json' },
    dayjs: null,
    antd: null,
    notes:
      'DRIFT — the newest language, and the sharpest example of why this registry ' +
      'exists. Added to presenter + audience only; aha-report, aha-survey and ' +
      'aha-team-management have NO Azerbaijani entry, so they silently render English ' +
      'for an Azerbaijani session. dayjs and antd are null because NO app has chosen ' +
      'either yet — they were NOT guessed. Whoever adds `az` to a consumer must pick ' +
      'them deliberately and record them here.',
  },
  {
    code: 'sr-Latn',
    name: 'Serbian (Latin)',
    aliases: [],
    apps: {
      presenter: 'sr-latn',
      audience: 'sr-latn',
      report: 'sr-latn',
      survey: 'sr-Latn',
      team: 'sr-latn',
    },
    files: {
      presenter: 'AhaSlides_Serbian_Latin.json',
      audience: 'AhaSlides_Serbian_Latin.json',
    },
    dayjs: 'sr',
    antd: 'sr_RS',
    notes:
      'Canonical uses BCP-47 script-subtag casing (`sr-Latn`). Presenter/audience/report/' +
      'team use all-lowercase `sr-latn`; aha-team-management sets i18next `lowerCaseLng: ' +
      'true` specifically to keep that. This is a CASE difference, not an alias: ' +
      'resolution is case-insensitive, so both spellings resolve to `sr-Latn`.',
  },
  {
    code: 'sr-Cyrl',
    name: 'Serbian (Cyrillic)',
    aliases: [],
    apps: {
      presenter: 'sr-cyrl',
      audience: 'sr-cyrl',
      report: 'sr-cyrl',
      survey: 'sr-Cyrl',
      team: 'sr-cyrl',
    },
    files: {
      presenter: 'AhaSlides_Serbian_Cyrillic.json',
      audience: 'AhaSlides_Serbian_Cyrillic.json',
    },
    dayjs: 'sr-cyrl',
    antd: 'sr_RS',
    notes:
      'DELIBERATE GAP — DO NOT "FIX". antd has no Cyrillic Serbian pack, so both ' +
      'aha-report and aha-survey borrow the LATIN-script sr_RS pack; built-ins render ' +
      'in Latin script while strings/dates are Cyrillic. That is the existing, ' +
      'intentional behavior.',
  },
];
