import type { LanguageEntry } from './types.js';

/**
 * The canonical AhaSlides language registry — the ONE standard.
 *
 * Every `code` here is ISO 639-1, with a BCP-47 script subtag where a script
 * distinction exists. Where an app uses something else today, the app is
 * non-compliant and that fact lives in `./non-compliance.ts`, NOT here. This
 * file must never grow an app-shaped field again: the moment the standard can
 * express "…and presenter says `kr`", the standard has conceded.
 *
 * THIS FILE IS DATA — a code, a name, two pack values, and no field to write
 * prose in. That is deliberate: a `notes` field existed and grew to a quarter of
 * this file, restating what the records below already said. Where prose goes:
 *   - an app must change            -> `./non-compliance.ts` (NON_COMPLIANCE)
 *   - one code, different content   -> `./non-compliance.ts` (CONTENT_DIVERGENCES)
 *   - narrative for no single entry -> README
 *   - "don't 'fix' this value"      -> a test that fails and says why. Every
 *      deliberate value here (sq's en_US, sr-Cyrl's sr_RS, no's nb, the nulls)
 *      is pinned in `./languages.test.ts` — a comment never stopped anyone.
 *
 * SOURCES for the language SET and the dayjs/antd choices (all read from
 * `origin/staging`, re-verified 2026-07-15). Do not edit this file from memory
 * or from a local checkout — see the README's "Adding a language".
 *
 * - language set:
 *     stpancras-presenter-app  src/utils/language/index.js        (`messages`)
 *     stpancras-audience-app   src/utils/language/index.js        (`messages`)
 * - antd pack (Vue):
 *     aha-report               src/utils/language.ts              (`antdLocaleLoaders`)
 * - antd pack (React) + dayjs code:
 *     aha-survey               frontend/src/i18n/applyLocale.ts   (`RESOURCES`)
 *     aha-survey               frontend/src/i18n/localeMapping.ts (`SUPPORTED`)
 *
 * 33 languages. The presenter's `messages` map has 34 keys, but `sl` and `si`
 * both load AhaSlides_Slovenia.json — two codes, one language. `si` is not a
 * 34th language; it is a defect, recorded in the non-compliance record.
 */
export const LANGUAGES: readonly LanguageEntry[] = [
  {
    code: 'en',
    name: 'English',
    dayjs: 'en',
    antd: 'en_US',
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    dayjs: 'vi',
    antd: 'vi_VN',
  },
  {
    code: 'es',
    name: 'Spanish',
    dayjs: 'es',
    antd: 'es_ES',
  },
  {
    code: 'pt',
    name: 'Portuguese',
    dayjs: 'pt-br',
    antd: 'pt_PT',
  },
  {
    code: 'fr',
    name: 'French',
    dayjs: 'fr',
    antd: 'fr_FR',
  },
  {
    code: 'de',
    name: 'German',
    dayjs: 'de',
    antd: 'de_DE',
  },
  {
    code: 'id',
    name: 'Indonesian',
    dayjs: 'id',
    antd: 'id_ID',
  },
  {
    code: 'it',
    name: 'Italian',
    dayjs: 'it',
    antd: 'it_IT',
  },
  {
    code: 'tr',
    name: 'Turkish',
    dayjs: 'tr',
    antd: 'tr_TR',
  },
  {
    code: 'ja',
    name: 'Japanese',
    dayjs: 'ja',
    antd: 'ja_JP',
  },
  {
    code: 'nl',
    name: 'Dutch',
    dayjs: 'nl',
    antd: 'nl_NL',
  },
  {
    code: 'ru',
    name: 'Russian',
    dayjs: 'ru',
    antd: 'ru_RU',
  },
  {
    code: 'pl',
    name: 'Polish',
    dayjs: 'pl',
    antd: 'pl_PL',
  },
  {
    code: 'da',
    name: 'Danish',
    dayjs: 'da',
    antd: 'da_DK',
  },
  {
    code: 'zh',
    name: 'Chinese (Simplified)',
    dayjs: 'zh-cn',
    antd: 'zh_CN',
  },
  {
    code: 'sl',
    name: 'Slovenian',
    dayjs: 'sl',
    antd: 'sl_SI',
  },
  {
    code: 'lv',
    name: 'Latvian',
    dayjs: 'lv',
    antd: 'lv_LV',
  },
  {
    code: 'cs',
    name: 'Czech',
    dayjs: 'cs',
    antd: 'cs_CZ',
  },
  {
    code: 'ko',
    name: 'Korean',
    dayjs: 'ko',
    antd: 'ko_KR',
  },
  {
    code: 'no',
    name: 'Norwegian',
    dayjs: 'nb',
    antd: 'nb_NO',
  },
  {
    code: 'sv',
    name: 'Swedish',
    dayjs: null,
    antd: 'sv_SE',
  },
  {
    code: 'el',
    name: 'Greek',
    dayjs: 'el',
    antd: 'el_GR',
  },
  {
    code: 'lt',
    name: 'Lithuanian',
    dayjs: 'lt',
    antd: 'lt_LT',
  },
  {
    code: 'hr',
    name: 'Croatian',
    dayjs: 'hr',
    antd: 'hr_HR',
  },
  {
    code: 'is',
    name: 'Icelandic',
    dayjs: 'is',
    antd: 'is_IS',
  },
  {
    code: 'bg',
    name: 'Bulgarian',
    dayjs: 'bg',
    antd: 'bg_BG',
  },
  {
    code: 'ro',
    name: 'Romanian',
    dayjs: 'ro',
    antd: 'ro_RO',
  },
  {
    code: 'sk',
    name: 'Slovak',
    dayjs: 'sk',
    antd: 'sk_SK',
  },
  {
    code: 'hu',
    name: 'Hungarian',
    dayjs: 'hu',
    antd: 'hu_HU',
  },
  {
    code: 'sq',
    name: 'Albanian',
    dayjs: 'sq',
    antd: 'en_US',
  },
  {
    code: 'az',
    name: 'Azerbaijani',
    dayjs: null,
    antd: null,
  },
  {
    code: 'sr-Latn',
    name: 'Serbian (Latin)',
    dayjs: 'sr',
    antd: 'sr_RS',
  },
  {
    code: 'sr-Cyrl',
    name: 'Serbian (Cyrillic)',
    dayjs: 'sr-cyrl',
    antd: 'sr_RS',
  },
];
