name: "Production & Canary Deploy"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build-app
        with:
          repository_url: 018208337430.dkr.ecr.us-east-1.amazonaws.com/us01/plugins
          commit_sha: ${{ github.sha }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1

  deploy_canary:
    name: Deploy Canary
    runs-on: ubuntu-latest
    needs: build
    if: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Frontend
        uses: ./.github/actions/deploy-app
        with:
          s3_bucket: ${{ secrets.AWS_S3_BUCKET_CANARY }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1

      - name: Deploy Backend
        uses: ./.github/actions/deploy-ecs
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          repository_url: 018208337430.dkr.ecr.us-east-1.amazonaws.com/us01/plugins
          commit_sha: ${{ github.sha }}
          ecs_cluster: us01-plugins
          ecs_service: us01-plugins-canary
          ecs_task_definition: ecs/tasks/us01-plugins-backend-canary.json

  deploy_production:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: build
    if: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Frontend
        uses: ./.github/actions/deploy-app
        with:
          s3_bucket: ${{ secrets.AWS_S3_BUCKET_PRODUCTION }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1

      - name: Deploy Backend
        uses: ./.github/actions/deploy-ecs
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          repository_url: 018208337430.dkr.ecr.us-east-1.amazonaws.com/us01/plugins
          commit_sha: ${{ github.sha }}
          ecs_cluster: us01-plugins
          ecs_service: us01-plugins-default
          ecs_task_definition: ecs/tasks/us01-plugins-backend-default.json
