name: "Update Slide Types - staging"

on:
  workflow_dispatch:
    branches:
      - staging
  repository_dispatch:
    types: [update-slide-types-submodules]

jobs:
  update-modules:
    runs-on:
      group: github-runner-arm64
    if: github.ref == 'refs/heads/staging'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # note those token is used to checkout code from submodule repo 
          # but it seem to be persisted to use for next step 
          # so we need tokens that can read for all submodules
          # and write for main repo
          token: ${{ secrets.GH_PLUGINS_PAT }}
          submodules: recursive
      - name: Update submodules
        uses: ./.github/actions/checkout
        with:
          plugins_branch: staging
          target_branch: staging
